# Generated by Django 6.1 on 2026-08-28 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Expertises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EngineerExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert'), ('Lead / Specialist', 'Lead / Specialist')], default='Intermediate', max_length=50)),
                ('engineer', models.ForeignKey(limit_choices_to={'role': 'Engineer'}, on_delete=django.db.models.deletion.CASCADE, related_name='engineer_expertises', to=settings.AUTH_USER_MODEL)),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_engineers', to='services.expertise')),
            ],
            options={
                'verbose_name': 'Engineer Expertise',
                'verbose_name_plural': 'Engineer Expertises',
                'unique_together': {('engineer', 'expertise')},
            },
        ),
    ]
