# Generated by Django 6.1 on 2026-09-04 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_engineerexpertise_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineerexpertise',
            options={'ordering': ['-created_at', 'expertise__name'], 'verbose_name': 'Engineer Expertise', 'verbose_name_plural': 'Engineer Expertises'},
        ),
        migrations.AddField(
            model_name='engineerexpertise',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='engineerexpertise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerexpertise',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineerexpertise',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='engineerexpertise',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Verification'), ('Approved', 'Verified / Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
    ]
