# Generated by Django 6.1 on 2026-09-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientprofile_engineerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Engineer', 'Software Engineer'), ('Admin', 'Admin')], db_index=True, default='Client', max_length=20),
        ),
    ]
